### ISSUE TITLE
Full Instructions Required

### ISSUE THREAD

**Issue by joeyoropesa-dev** [tesla-software/jmbg#2]
What about for beginners that are just installed php and composer and done all the things you wrote here? composer test command doesn't do anything since the command is not defined yet and codes for generation and validation are not capable of entering via command prompt since it requires to run inside the composer but how to do it I'm not sure

Can you write the full instructions for this or write batch (.bat) and .sh files for auto-installation and setup

Thank you in advance!

**Comment by karlomikus** [comment]
Hello, instructions depend on what do you want to do.

If you want to use this in your existing PHP project than you need to add it into your project as a dependency with `composer require tesla-software/jmbg` and then use it as any other composer dependency.

If you want to open a pull request or run this package tests then you need to.
- Clone this repo
- Run `composer install`
- Run the tests with `composer test`

If you are complete beginner in PHP [maybe reading about composer here](https://phptherightway.com/#composer_and_packagist) will be some help.

**Comment by joeyoropesa-dev** [comment]
> Hello, instructions depend on what do you want to do.
> 
> If you want to use this in your existing PHP project than you need to add it into your project as a dependency with `composer require tesla-software/jmbg` and then use it as any other composer dependency.
> 
> If you want to open a pull request or run this package tests then you need to.
> - Clone this repo
> - Run `composer install`
> - Run the tests with `composer test`
> 
> If you are complete beginner in PHP [maybe reading about composer here](https://phptherightway.com/#composer_and_packagist) will be some help.

How can I for example generate jmbg (for tests but with specific configurations like target country, gender and birthday date) with composer test


And also, what php and composer version is recommended (I'm using Windows)

**Comment by karlomikus** [comment]
Current support is for PHP 8.0-8.2, composer version doesn't really matter.

`composer test` is only intended to run the package unit tests and is not used in the distributed package.

If you want to use this package in your own tests you could use something like this:

```php
<?php

use Tesla\JMBG\Generator;

class MyTest extends TestCase
{
    public function testMyJMBG(): void
    {
        $gen = new Generator();

        $randomFakeJMBG = $gen->fake();
        $specificJMBG = $gen->fake(25, 9, 992, '57', '321');
    }
}
```

But, anyway, basic PHP support is offtopic for this repository.
